A few suggestions
iwasrobbed/Swift-CheatSheet pull request #20
Opened 2016-11-08 22:59 UTC by jgclark

I don't claim to be an expert here, but just trying to fill some gaps, as I learn Swift myself.

2016-11-08 23:01 UTC, timvermeulen commented
fibonacci[5..8]

Isn't this Swift 1?

2016-11-09 00:29 UTC, iwasrobbed requested changes
Thanks for submitting this! A couple of comments to address, but I'd be happy to merge after you push an update!

2016-11-09 00:29 UTC, iwasrobbed commented on README.md
> +`[key:value]` | Returns a `Dictionary` object (arrays with no ordering, looking up values through keys)
Dictionaries are probably better explained as hash tables versus arrays. E.g. https://github.com/raywenderlich/swift-algorithm-club/tree/master/Hash%20Table

2016-11-09 00:29 UTC, iwasrobbed commented on README.md
> +The built-in methods and accessors for Strings are different in Swift 1.x, 2.1+, and 3.0, and so are not covered here.
You can likely leave this out since the intention of this cheat sheet is to be for Swift 3+ (and eventually will be Swift 4+ once that's released)

2016-11-09 00:29 UTC, iwasrobbed commented on README.md
> +fibonacci[0..fibonacci.endIndex] // all except last item
The above two lines don't compile; please ensure you check all code examples in an Xcode 8+ Playground before submitting

2016-11-09 00:29 UTC, iwasrobbed commented on README.md
> +let airlines = [ "BA" : "British Airways", "AA" : "American Airlines" ]
`let` should be `var`

2016-11-09 00:29 UTC, iwasrobbed commented on README.md
> +func vend() throws -> String
Missing the opening `{` for the function

2016-11-11 20:28 UTC, jgclark commented
This is my first time trying to do a pull request. I've made some mods as suggested, but I'm not sure what the next step is. Do I just wait, or do I have to re-submit in some way, @iwasrobbed?

2016-11-11 22:26 UTC, iwasrobbed commented
@jgclark No worries, you're doing great so far! I added a couple of comments this time around. I'd ask that you run any code you submit in the future in an Xcode Playground before submitting so you save time from us having to run it ourselves 👍

2016-11-11 22:27 UTC, iwasrobbed requested changes

2016-11-11 22:27 UTC, iwasrobbed commented on README.md
> +fibonacci[0...fibonacci.endIndex] // gives all except last item
This line doesn't do what your comment says (and will throw a runtime error)

2016-11-11 22:27 UTC, iwasrobbed commented on README.md
> +var example = [ "hi", "there", 23, true ]
If you were to run this code in an Xcode playground, it'll fail to compile and ask you to be explicit in declaring it as `[Any]`

Also, nitpick on code formatting / whitespace:

```swift
var example: [Any] = ["hi", "there", 23, true]
print("item at index 0: \(example[0])") // prints "hi"
example.insert("new item", at: 1) // "new item" is now the second in the list
example.remove(at: 0)
```

2016-11-11 22:27 UTC, iwasrobbed commented on README.md
> +The built-in methods and accessors for Strings are different in Swift 1.x, 2.1+, and 3.0, and so are not covered here.
Reminder to remove this text please

2016-11-11 22:27 UTC, iwasrobbed commented on README.md
> +airlines["PA"] = nil        // removing an item
Might be good to include this as well since it's more commonly used:

```swift
airlines.removeValue(forKey: "PA")
```

2016-12-13 08:08 UTC, ZiyoMuhammad commented
bir tin

2017-08-03 05:25 UTC, iwasrobbed commented
Closing as this PR has gone stale. Feel free to re-open once comments are addressed

2017-08-03 05:25 UTC, closed without merging